[package]
name = "libforge"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
glam = "0.31.0"
pollster = "0.4.0"
raw-window-handle = "0.6.0"
thiserror = "2.0.18"
wgpu = "27.0.1"
winit = "0.30.12"
